# Generated by Django 2.2.28 on 2026-03-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_seven_five_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
