# Generated by Django 3.2.25 on 2026-03-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_seven_five_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haiku',
            name='haiku_picture',
            field=models.ImageField(blank=True, null=True, upload_to='haiku_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
