# Generated by Django 6.0.3 on 2026-03-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("five_seven_five_app", "0002_alter_comment_id_alter_follow_id_and_more"),
        ("five_seven_five_app", "0002_auto_20260324_1234"),
        ("five_seven_five_app", "0002_auto_20260324_2303"),
    ]

    operations = []
