# Generated by Django 6.0.3 on 2026-03-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("five_seven_five_app", "0003_merge_20260325_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haiku",
            name="haiku_picture",
            field=models.ImageField(blank=True, null=True, upload_to="haiku_pictures/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default_pic.png",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
